Repository banzaicloud/banzai-charts, pull requests merged in 2019-05, with the labels that each got.

#764 Add psp to pvc-operator
  pvc-operator/Chart.yaml
  pvc-operator/templates/deployment.yaml
  pvc-operator/templates/psp.yaml
  pvc-operator/templates/rbac.yaml
  pvc-operator/values.yaml
Labels: security

#772 PSP to spot-scheduler
  spot-scheduler/Chart.yaml
  spot-scheduler/README.md
  spot-scheduler/templates/deployment.yaml
  spot-scheduler/templates/psp.yaml
  spot-scheduler/templates/rbac.yaml
  spot-scheduler/values.yaml
Labels: security

#769 Add PSP to kubernetes-dashboard
  kubernetes-dashboard/Chart.yaml
  kubernetes-dashboard/templates/deployment.yaml
  kubernetes-dashboard/templates/psp.yaml
  kubernetes-dashboard/templates/role.yaml
  kubernetes-dashboard/templates/rolebinding.yaml
  kubernetes-dashboard/values.yaml
Labels: security

#770 Define PSP for nodepool-labels-operator
  nodepool-labels-operator/Chart.yaml
  nodepool-labels-operator/templates/deployment.yaml
  nodepool-labels-operator/templates/psp.yaml
  nodepool-labels-operator/templates/rbac.yaml
  nodepool-labels-operator/values.yaml
Labels: security

#771 PSP to pipeline-cluster-ingress
  pipeline-cluster-ingress/Chart.yaml
  pipeline-cluster-ingress/templates/_helpers.tpl
  pipeline-cluster-ingress/templates/psp.yaml
  pipeline-cluster-ingress/templates/rbac.yaml
  pipeline-cluster-ingress/values.yaml
Labels: security

#815 vault-secret-webhook: add namespaceSelector variable
  vault-secrets-webhook/Chart.yaml
  vault-secrets-webhook/README.md
  vault-secrets-webhook/templates/apiservice-webhook.yaml
  vault-secrets-webhook/values.yaml
Labels: vault

#831 cadence: use the same cassandra image for deployment and check
  cadence/Chart.yaml
  cadence/templates/server-deployment.yaml
  cadence/values.yaml
Labels: cadence

#788 cadence: add prometheus configuration
  cadence/README.md
  cadence/templates/server-configmap.yaml
  cadence/templates/server-deployment.yaml
  cadence/templates/web-service.yaml
  cadence/values.yaml
Labels: cadence, community
