Repository banzaicloud/banzai-charts, pull requests merged in 2019-02, with the labels that each got.

#653 vault operator version 0.4.7, new operator flags, serviceAccount/Name
  vault-operator/Chart.yaml
  vault-operator/templates/crd.yaml
  vault-operator/templates/deployment.yaml
  vault-operator/templates/role.yaml
  vault-operator/values.yaml
Labels: community, vault

#648 [thanos] - ingress for query service
  thanos/templates/query-ingress.yml
  thanos/values.yaml
Labels: community, enhancement

#645 Make the chart work with S3 buckets
  thanos/templates/compact-deployment.yaml
  thanos/templates/configmap.yaml
  thanos/templates/query-deployment.yaml
  thanos/templates/secret.yaml
  thanos/templates/store-deployment.yaml
  thanos/values.yaml
Labels: community, enhancement

#660 dex: change connectors to dict
  dex/Chart.yaml
  dex/README.md
  dex/templates/config.yaml
  dex/values.yaml
Labels: dex

#661 Fix pipeline deployment strategy location
  pipeline/Chart.yaml
  pipeline/templates/deployment.yaml
Labels: bug

#673 thanos - fix the data-dir value to actually use the empty volume
  thanos/templates/store-deployment.yaml
Labels: bug, community

#670 dex: enable grpc
  dex/Chart.yaml
  dex/templates/config.yaml
  dex/values.yaml
Labels: dex

#672 [thanos] - added securityContext management capabilities
  thanos/Chart.yaml
  thanos/README.md
  thanos/templates/compact-deployment.yaml
  thanos/templates/query-deployment.yaml
  thanos/templates/store-deployment.yaml
  thanos/values.yaml
Labels: community, enhancement
